version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      shinyproxy-net:
  shinyproxy:
    image: openanalytics/shinyproxy
    user: root:root
    container_name: shinyproxy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
    networks:
      shinyproxy-net:
        ipv4_address: 192.168.92.21 
networks:
  shinyproxy-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"